<a href="https://colab.research.google.com/github/quastarK/Tensorflow_colab/blob/main/Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

## 랭크 0


In [ ]:
mammal = tf.Variable("코끼리", tf.string)
ignition = tf.Variable(451,tf.int16)
floating = tf.Variable(3.141592653,tf.float64)
its_complicated = tf.Variable(12.3-4.85j,tf.complex64)

In [ ]:
print(mammal)
print(ignition)
print(floating)
print(its_complicated)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'\xec\xbd\x94\xeb\x81\xbc\xeb\xa6\xac'>
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=451>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.1415927>
<tf.Variable 'Variable:0' shape=() dtype=complex128, numpy=(12.3-4.85j)>


## 랭크 1

In [7]:
mystr = tf.Variable(["안녕하세요"], tf.string)
cool_numbers = tf.Variable([3.14159,2.71828],tf.float32)
first_primes = tf.Variable([2,3,5,7,11],tf.int32)
its_very_complicated = tf.Variable([12.3-4.85j,7.5-6.23j],tf.complex64)

In [8]:
print(mystr)
print(cool_numbers)
print(first_primes)
print(its_very_complicated)

<tf.Variable 'Variable:0' shape=(1,) dtype=string, numpy=
array([b'\xec\x95\x88\xeb\x85\x95\xed\x95\x98\xec\x84\xb8\xec\x9a\x94'],
      dtype=object)>
<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([3.14159, 2.71828], dtype=float32)>
<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([ 2,  3,  5,  7, 11], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2,) dtype=complex128, numpy=array([12.3-4.85j,  7.5-6.23j])>


## 고차원 랭크

랭크 2 tf.Tensor 객체는 최소 한 개 이상의 열과 행으로 구성됩니다.

In [10]:
mymat = tf.Variable([[7],[11]], tf.int16)
myxor = tf.Variable([[False,True],[True,False]], tf.bool)
linear_squares = tf.Variable([[4],[9],[16],[25]], tf.int32)
squarish_squares = tf.Variable([[4,9],[16,25]], tf.int32)
rank_of_squares = tf.rank(squarish_squares)
mymatC = tf.Variable([[7],[11]],tf.int32)

In [13]:
print(mymat)
print(myxor)
print(linear_squares)
print(squarish_squares)
print(rank_of_squares)
print(mymatC)

<tf.Variable 'Variable:0' shape=(2, 1) dtype=int32, numpy=
array([[ 7],
       [11]], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2, 2) dtype=bool, numpy=
array([[False,  True],
       [ True, False]])>
<tf.Variable 'Variable:0' shape=(4, 1) dtype=int32, numpy=
array([[ 4],
       [ 9],
       [16],
       [25]], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[ 4,  9],
       [16, 25]], dtype=int32)>
tf.Tensor(2, shape=(), dtype=int32)
<tf.Variable 'Variable:0' shape=(2, 1) dtype=int32, numpy=
array([[ 7],
       [11]], dtype=int32)>


고차원 랭크 텐서는 n-차원 배열로 구성됩니다.


In [17]:
my_image = tf.zeros([10,299,299,3]) # 배치 x 높이 x 너비 x 색상

In [18]:
print(my_image.shape)

(10, 299, 299, 3)


##Tf.Tensor 원소 참조하기

tf.Tensor는 n-차원 배열로 구성되어 있기 떄문에, tf.Tensor 원소 하나에 접근하기 위해서는 n개의 인덱스가 필요합니다

랭크 0 텐서 (스칼라)인 경우 이미 하나의 숫자이기 때문에 인덱스가 필요없습니다.

랭크 1 텐서 (벡터)인 경우 숫자 하나에 접근하기 위해서는 인덱스 하나를 전달해야 합니다.

In [24]:
my_matrix = tf.Variable([ [1,2,3,4],
                          [2,3,4,5],
                          [3,4,5,6],
                          [4,5,6,7]],tf.int16)
my_scalar = my_matrix[2]
print(my_scalar)

tf.Tensor([3 4 5 6], shape=(4,), dtype=int32)


In [25]:
my_scalar = my_matrix[1,2]
print(my_scalar)

tf.Tensor(4, shape=(), dtype=int32)


그러나, 인덱스를 한 개만 전달한다면 다음과 같이 행렬의 부분 벡터를 반환합니다

: 표기는 "해당 차원을 남겨라"라는 파이썬 슬라이싱 문법입니다. 이러한 표기법은 고차원 텐서에서 부분 벡터와 부분 행렬, 다른 부분 텐서들까지도 접근할 수 있도록 만들어 주기 때문에 유용합니다.

In [26]:
my_row_vector = my_matrix[2]
my_column_vector = my_matrix[:,3]

In [29]:
print(my_matrix)

<tf.Variable 'Variable:0' shape=(4, 4) dtype=int32, numpy=
array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]], dtype=int32)>


In [27]:
print(my_row_vector)

tf.Tensor([3 4 5 6], shape=(4,), dtype=int32)


In [28]:
print(my_column_vector)

tf.Tensor([4 5 6 7], shape=(4,), dtype=int32)


In [35]:
print(my_matrix[1:3])

tf.Tensor(
[[2 3 4 5]
 [3 4 5 6]], shape=(2, 4), dtype=int32)


In [39]:
print(my_matrix[:,1:3])

tf.Tensor(
[[2 3]
 [3 4]
 [4 5]
 [5 6]], shape=(4, 2), dtype=int32)


## 형태 (shape)

텐서의 형태는 각 차원에 있는 원소 개수로 표현됩니다.
텐서플로는 그래프 계산 과정에서 자동으로 텐서 형태를 추론합니다.
이렇게 추론된 형태는 랭크를 알고 있는 경우도 있고, 그렇지 않은 경우도 있습니다.

만약에 랭크를 알고 있는 경우라도 각 차원의 원소 개수를 알고 있는 경우도 잇고 그렇지 않는 경우도 있습니다.

텐서플로 문서에서 텐서 차원을 표현하기 위해서 3가지 용어를 사용합니다. :: 랭크, 형태, 차원

In [42]:
my_matrix = tf.zeros([3,2])
zeros = tf.zeros(my_matrix.shape[1])
print(my_matrix.shape)
print(zeros.shape)

(3, 2)
(2,)


### tf.Tensor 형태 변경
원소 개수를 유지하면서 tf.Tensor 형태를 변경할 수 있다 : tf.reshape

In [48]:
rank_three_tensor = tf.ones([3,4,5])            # 3x4x5 = 60
matrix = tf.reshape(rank_three_tensor,[6,10])   # 6x10 = 60
matrixB = tf.reshape(matrix,[3,-1])             # -1 차원 크기를 계산하여 자동으로 계산하라는 의미 -> [3,20] 으로 바뀜
matrixA = tf.reshape(matrixB,[4,3,-1])          # 4x3x5 으로 바꾸라는 말

In [49]:
print(rank_three_tensor.shape)
print(matrix.shape)
print(matrixB.shape)
print(matrixA.shape)

(3, 4, 5)
(6, 10)
(3, 20)
(4, 3, 5)


In [50]:
matrix_error = tf.reshape(matrixB,[12,3,-1])  # 원소의 갯수가 동일하게 유지되지 않으므로 에러가 발생

InvalidArgumentError: {{function_node __wrapped__Reshape_device_/job:localhost/replica:0/task:0/device:CPU:0}} Input to reshape is a tensor with 60 values, but the requested shape requires a multiple of 36 [Op:Reshape]

### 자료형 (data type)

tf.DType 으로 전체 자료형 확인 가능

tf.Tensor가 한 개이상의 자료형을 가지는 것은 불가능 합니다.
임의의 데이터 구조를 직렬화한 string를 저장한 tf.Tensor는 예와

tf.cast를 이용해서 tf.Tensor의 자료형을 다른 것으로 변경하는 것이 가능

In [54]:
constant_tensor = tf.constant([1,2,3])
float_tensor = tf.cast(constant_tensor, dtype=tf.float32)

In [55]:
print(constant_tensor.dtype)
print(float_tensor.dtype)

<dtype: 'int32'>
<dtype: 'float32'>


## 텐서 계산하기 (evaluate)

In [58]:
constant = tf.constant([1,2,3])
tensor = constant*constant
print(tensor)     #tensor.eval() <- tensorflow 1.0

tf.Tensor([1 4 9], shape=(3,), dtype=int32)
