<a href="https://colab.research.google.com/github/quastarK/Tensorflow_colab/blob/main/Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

## 랭크 0


In [ ]:
mammal = tf.Variable("코끼리", tf.string)
ignition = tf.Variable(451,tf.int16)
floating = tf.Variable(3.141592653,tf.float64)
its_complicated = tf.Variable(12.3-4.85j,tf.complex64)

In [ ]:
print(mammal)
print(ignition)
print(floating)
print(its_complicated)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'\xec\xbd\x94\xeb\x81\xbc\xeb\xa6\xac'>
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=451>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.1415927>
<tf.Variable 'Variable:0' shape=() dtype=complex128, numpy=(12.3-4.85j)>


## 랭크 1

In [7]:
mystr = tf.Variable(["안녕하세요"], tf.string)
cool_numbers = tf.Variable([3.14159,2.71828],tf.float32)
first_primes = tf.Variable([2,3,5,7,11],tf.int32)
its_very_complicated = tf.Variable([12.3-4.85j,7.5-6.23j],tf.complex64)

In [8]:
print(mystr)
print(cool_numbers)
print(first_primes)
print(its_very_complicated)

<tf.Variable 'Variable:0' shape=(1,) dtype=string, numpy=
array([b'\xec\x95\x88\xeb\x85\x95\xed\x95\x98\xec\x84\xb8\xec\x9a\x94'],
      dtype=object)>
<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([3.14159, 2.71828], dtype=float32)>
<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([ 2,  3,  5,  7, 11], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2,) dtype=complex128, numpy=array([12.3-4.85j,  7.5-6.23j])>


## 고차원 랭크

랭크 2 tf.Tensor 객체는 최소 한 개 이상의 열과 행으로 구성됩니다.

In [10]:
mymat = tf.Variable([[7],[11]], tf.int16)
myxor = tf.Variable([[False,True],[True,False]], tf.bool)
linear_squares = tf.Variable([[4],[9],[16],[25]], tf.int32)
squarish_squares = tf.Variable([[4,9],[16,25]], tf.int32)
rank_of_squares = tf.rank(squarish_squares)
mymatC = tf.Variable([[7],[11]],tf.int32)

In [13]:
print(mymat)
print(myxor)
print(linear_squares)
print(squarish_squares)
print(rank_of_squares)
print(mymatC)

<tf.Variable 'Variable:0' shape=(2, 1) dtype=int32, numpy=
array([[ 7],
       [11]], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2, 2) dtype=bool, numpy=
array([[False,  True],
       [ True, False]])>
<tf.Variable 'Variable:0' shape=(4, 1) dtype=int32, numpy=
array([[ 4],
       [ 9],
       [16],
       [25]], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[ 4,  9],
       [16, 25]], dtype=int32)>
tf.Tensor(2, shape=(), dtype=int32)
<tf.Variable 'Variable:0' shape=(2, 1) dtype=int32, numpy=
array([[ 7],
       [11]], dtype=int32)>


고차원 랭크 텐서는 n-차원 배열로 구성됩니다.


In [17]:
my_image = tf.zeros([10,299,299,3]) # 배치 x 높이 x 너비 x 색상

In [18]:
print(my_image.shape)

(10, 299, 299, 3)
